version: '3.5'
services:
 nginx:
  restart: unless-stopped
  image: nginx
  networks:
   net_frontend:
   net_backend:
  depends_on:
   - backend1
   - backend2
  ports:
   - 80:80/tcp
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf:ro

 backend1:
  restart: unless-stopped
  image: mpepping/whoami
  networks:
    net_backend:
  environment:
    - MESSAGE=backend1

 backend2:
  restart: unless-stopped
  image: mpepping/whoami
  networks:
    net_backend:
  environment:
    - MESSAGE=backend2

networks:
  net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24


